### **Task 4 : Question on Numpy**
**Reg ID: GO_STP_10493**

**Import the numpy package under the name np and Print the numpy version and the configuration**

In [ ]:
import numpy as np
print("Version: {}".format(np.__version__))
print(np.show_config())

Version: 1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


**Create a null vector of size 10**

In [ ]:
x= np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a= np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
type(a)

numpy.ndarray

**How to find number of dimensions, bytes per element and bytes of memory used?**

In [ ]:

import sys
a = np.arange(1,10).reshape(3,3)
print(f"dimension: {a.shape}")
print("Bytes per Element: {}".format(a.itemsize))
print("Memory size of numpy array is " +str(a.size*a.itemsize))



dimension: (3, 3)
Bytes per Element: 8
Memory size of numpy array is 72


**Create a null vector of size 10 but the fifth value which is 1**

In [ ]:
a = (np.arange(10)==4).astype(int)
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

**Create a vector with values ranging from 10 to 49**


In [ ]:
a=np.arange(10,50)
print(a)

# Reverse a vector (first element becomes last)

print("\n Reversed vector\n",np.flipud(a))


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 Reversed vector
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**Create a 3x3 matrix with values ranging from 0 to 8**

In [ ]:

a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Find indices of non-zero elements from [1,2,0,0,4,0]**

In [ ]:
a= np.array([1,2,0,0,4,0])

print("indexes of non-zero elements are:", np.nonzero(a))

indexes of non-zero elements are: (array([0, 1, 4]),)


 **Create a 3x3 identity matrix**

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Create a 3x3x3 array with random values**

In [ ]:
np.random.random((3,3,3))

array([[[0.02190034, 0.75452266, 0.6255544 ],
        [0.80657637, 0.34802348, 0.00380537],
        [0.08913666, 0.16934539, 0.73023891]],

       [[0.75703895, 0.67333809, 0.04060223],
        [0.20491815, 0.83972498, 0.03012421],
        [0.94986874, 0.58630052, 0.39176981]],

       [[0.72766803, 0.18187769, 0.56899865],
        [0.77378885, 0.86987623, 0.10605904],
        [0.40450675, 0.73660842, 0.69577759]]])

**Create a 10x10 array with random values and find the minimum and maximum values**

In [ ]:
a=np.random.random((10,10))
print('max value',a.max())
print('min value',a.min())
# Create a random vector of size 30 and find the mean value
vector = np.random.random(30)
print("Mean value is",vector.mean())
vector



max value 0.9858289873019561
min value 0.007280950496177052
Mean value is 0.5339807670678084


array([0.82279818, 0.49031196, 0.49067155, 0.11840311, 0.15334389,
       0.9598201 , 0.10219841, 0.66673563, 0.34263726, 0.43887875,
       0.68609477, 0.6688036 , 0.76586956, 0.63499792, 0.87272937,
       0.02072781, 0.68099517, 0.81483459, 0.66071465, 0.39202572,
       0.21647089, 0.1784969 , 0.83855389, 0.49774642, 0.2386957 ,
       0.48702777, 0.62620019, 0.67149788, 0.86681063, 0.61433072])

**Create a 2d array with 1 on the border and 0 inside**

In [ ]:
a=np.ones((10,10))
print(a)
print(" \nArray with 1 on the border and 0 inside:")
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 
Array with 1 on the border and 0 inside:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**How to add a border (filled with 0's) around an existing array? **

In [ ]:
arr = np.arange(1,10).reshape(3,3)
np.pad(arr, pad_width=1, mode='constant', constant_values=0 )

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

**How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
  [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]
Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20**

In [ ]:
arr= np.array([[ 1, 2, 3, 4 ,5, 6, 7], [ 8, 9, 10, 11, 12 ,13, 14]])
print(arr[1,5])
print(arr[0])
print(arr[:,2])
arr[1,5] = 20
print(arr[0][1::2])
print("Array after Replaced value\n",arr)

13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
Array after Replaced value
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


**How to Convert a 1D array to a 2D array with 2 rows**

In [ ]:
arr2 = np.arange(1,9)
print(arr2)
print("\n Converted 2D Array\n", arr2.reshape(2,4))

[1 2 3 4 5 6 7 8]

 Converted 2D Array
 [[1 2 3 4]
 [5 6 7 8]]


**Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
input:
   a = np.array([1,2,3])
Desired Output:
   array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])**

In [ ]:
a = np.array([1,2,3])
b = np.r_[np.repeat(a,3), np.tile(a,3)]
print("required pattern:\n", b)


required pattern:
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


**Write a program to show how Numpy taking less memory compared to Python List?**


In [ ]:
list1= range(1000)

import sys
a=10
print(sys.getsizeof(a))  # Memory allocated to a
print("\nBytes required for list storage ",sys.getsizeof(a)*len(list1))

a1= np.arange(1000)
print("\nBytes required for array storage ",a1.size*a1.itemsize)
print("So Numpy arrays requires less memory compared to list")


28

Bytes required for list storage  28000

Bytes required for array storage  8000
So Numpy arrays requires less memory compared to list


**Write a program to show how Numpy taking less time compared to Python List?
Calculating time required for lists operation**

In [ ]:
import time 
size =1000000
l1= range(size)
l2=range(size)
start = time.time()
result= [ (x+y) for x,y in zip(l1, l2)]
print("Time required for list operations is " +str((time.time() -start)*1000))

# Calculating time required for Numpy array operation
n1= np.arange(size)
n2=np.arange(size)
start = time.time()
result = n1 +n2
print("Time required for NumPy array operations is " +str((time.time() -start)*1000))



Time required for list operations is 120.67770957946777
Time required for NumPy array operations is 18.964052200317383
